# @@ibm-transadv@@ #
source: ibm-cp-applications-bundle/case/ibm-cp-applications/case.yaml
description: "Move from monolithic to microservices with DevOps methodologies and modernization toolkits"
images:
  - image: cp/icpa/icpa-app-nav-apis
  - image: cp/icpa/icpa-app-nav-cmds
  - image: cp/icpa/icpa-app-nav-controller
  - image: cp/icpa/icpa-app-nav-init
  - image: cp/icpa/icpa-app-nav-operator
  - image: cp/icpa/icpa-app-nav-ui
  - image: cp/icpa/icpa-app-nav-was-controller
  - image: cp/icpa/icpa-installer
  - image: cp/icpa/icpa-landing
  - image: cp/icpa/icpa-operator-registry
  - image: cp/icpa/transadv-db
  - image: cp/icpa/transadv-operator
  - image: cp/icpa/transadv-server
  - image: cp/icpa/transadv-ui
