source: ibm-cp-applications-le-bundle/case/ibm-cp-applications-le/case.yaml
description: "Move from monolithic to microservices with DevOps methodologies and modernization toolkits"
images:
  - image: cp/icpa/icpa-app-nav-apis
  - image: cp/icpa/icpa-app-nav-cmds
  - image: cp/icpa/icpa-app-nav-controller
  - image: cp/icpa/icpa-app-nav-init
  - image: cp/icpa/icpa-app-nav-operator
  - image: cp/icpa/icpa-app-nav-ui
  - image: cp/icpa/icpa-app-nav-was-controller
  - image: cp/icpa/icpa-installer-le
  - image: cp/icpa/icpa-landing-le
