source: ibm-cp-applications-bundle/case/ibm-cp-applications/case.yaml
description: "Move from monolithic to microservices with DevOps methodologies and modernization toolkits"
images:
  - image: cp/icpa/icpa-installer
  - image: cp/icpa/icpa-landing
