apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    cloudpak.ibm.com/version: "1.1.0"
  name: ibm-anyuid-hostaccess-clusterrole
rules:
- apiGroups:
  - policy
  resourceNames:
  - ibm-anyuid-hostaccess-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
